# Generated by Django 4.2.5 on 2023-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
